# Generated by Django 4.1.7 on 2023-04-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('text_kz', models.TextField()),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CycleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_practice', models.BooleanField(default=False)),
                ('cycle_kz', models.CharField(blank=True, choices=[('OOD', 'ООД'), ('BD', 'БП'), ('PD', 'КП'), ('DVO', 'ДВО'), ('IA', 'ҚА'), ('Empty', '')], default='', max_length=255)),
                ('cycle_ru', models.CharField(blank=True, choices=[('OOD', 'ООД'), ('BD', 'БД'), ('PD', 'ПД'), ('DVO', 'ДВО'), ('IA', 'ИА'), ('Empty', '')], default='', max_length=255)),
                ('cycle_en', models.CharField(blank=True, choices=[('OOD', 'OOD'), ('BD', 'BD'), ('PD', 'PD'), ('DVO', 'DVI'), ('IA', 'FA'), ('Empty', '')], default='', max_length=255)),
                ('component_kz', models.CharField(blank=True, choices=[('VK', 'ЖООК'), ('KV', 'ТК'), ('Empty', '')], default='', max_length=255)),
                ('component_ru', models.CharField(blank=True, choices=[('VK', 'ВК'), ('KV', 'КВ'), ('Empty', '')], default='', max_length=255)),
                ('component_en', models.CharField(blank=True, choices=[('VK', 'UK'), ('KV', 'EC'), ('Empty', '')], default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name_kz', models.CharField(max_length=255)),
                ('dep_name_ru', models.CharField(max_length=255)),
                ('dep_name_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name_kz', models.CharField(max_length=255)),
                ('module_name_ru', models.CharField(max_length=255)),
                ('module_name_en', models.CharField(max_length=255)),
                ('cycle_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_op.cyclecomponent')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCompetencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('text_kz', models.TextField()),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
                ('type', models.CharField(choices=[('General', 'Общий'), ('Professional', 'Профессиональный')], default='General', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('control_form_kz', models.CharField(max_length=255)),
                ('control_form_ru', models.CharField(max_length=255)),
                ('control_form_en', models.CharField(max_length=255)),
                ('course_code_kz', models.CharField(max_length=255)),
                ('course_code_ru', models.CharField(max_length=255)),
                ('course_code_en', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('competencies', models.ManyToManyField(blank=True, to='api_op.competencies')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_op.department')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_op.module')),
                ('prerequisite', models.ManyToManyField(blank=True, to='api_op.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectToChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ManyToManyField(to='api_op.subject')),
            ],
        ),
        migrations.AddField(
            model_name='competencies',
            name='professional_competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_op.professionalcompetencies'),
        ),
    ]
