# Generated by Django 4.1.7 on 2023-04-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_op', '0003_remove_module_cycle_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='cycle_component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_op.cyclecomponent'),
        ),
    ]
