# Generated by Django 4.1.7 on 2023-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_op', '0004_subject_cycle_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencies',
            name='professional_competency',
        ),
        migrations.AddField(
            model_name='competencies',
            name='type',
            field=models.CharField(choices=[('General', 'Общий'), ('Professional', 'Профессиональный')], default='General', max_length=255),
        ),
        migrations.DeleteModel(
            name='ProfessionalCompetencies',
        ),
    ]
