# Generated by Django 4.1.7 on 2023-04-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_op', '0006_alter_competencies_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_code_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_code_kz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_code_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
